export { default as loginIllustration } from './login-illustration.svg'
export { default as previewWatermark } from './preview-watermark.svg'
export { default as publicDashboardIllustration } from './public-dashboard-illustration.svg'
export { default as publicReportsIllustration } from './public-reports-illustration.svg'
export { default as publicTransactionsIllustration } from './public-transactions-illustration.svg'
