/* eslint-disable no-undef */
window.env = {}

window.env.VITE_VERSION = `$VITE_VERSION`
window.env.VITE_API_URL = `$VITE_API_URL`
window.env.VITE_ADMIN_EMAIL = `$VITE_ADMIN_EMAIL`

window.env.VITE_KEYCLOAK_URL = `$VITE_KEYCLOAK_URL`
window.env.VITE_KEYCLOAK_REALM = `$VITE_KEYCLOAK_REALM`
window.env.VITE_KEYCLOAK_CLIENT_ID = `$VITE_KEYCLOAK_CLIENT_ID`
window.env.VITE_KEYCLOAK_REDIRECT_URL = `$VITE_KEYCLOAK_REDIRECT_URL`
