client_body_temp_path /tmp/frontend-runtime/nginx/client_body;
proxy_temp_path       /tmp/frontend-runtime/nginx/proxy;
fastcgi_temp_path     /tmp/frontend-runtime/nginx/fastcgi;
uwsgi_temp_path       /tmp/frontend-runtime/nginx/uwsgi;
scgi_temp_path        /tmp/frontend-runtime/nginx/scgi;

server {
  listen 8080;
  root   /usr/share/nginx/html;
  index  index.html index.htm;

  # Security headers
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
  include /tmp/frontend-runtime/csp.conf;
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header X-Content-Type-Options "nosniff" always;

  location = /env.global.js {
    root /tmp/frontend-runtime;
    default_type application/javascript;
    expires -1;
  }

  location / {
    try_files $uri $uri/ /index.html;
    expires -1; # Set it to different value depending on your standard requirements
  }
  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
    root   /usr/share/nginx/html;
  }
}
