package org.cardanofoundation.reeve.indexer.model.domain;

public enum BalanceSheetCategories {
    CASH,
    CRYPTO_ASSETS,
    FINANCIAL_ASSETS,
    OTHER,
    CURRENT,
    NON_CURRENT,
    ASSETS,
    LIABILITIES,
    CAPITAL,
    ACCRUSAL_AND_SHORT_TERM_PROVISIONS,
    TRADE_ACCOUNTS_PAYABLE,
    PROVISIONS,
    PROFIT_OF_THE_YEAR,
    RESULTS_CARRIED_FORWARD,
    PREPAYMENTS,
    INTANGIBLE_ASSETS,
    INVESTMENTS,
    PROPERTY_PLANT_EQUIPMENT
}
